name: Create Release Branch and PR

on:
  schedule:
    - cron: '0 6 * * *'
    # - cron: '0 1 * * 4' # Every Thursday at 10:00 AM JST
  workflow_dispatch:
jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with: backend
      - name: Get the current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Create and push release branch
        run: |
          git branch release/${{ env.DATE }}
          git push origin release/${{ env.DATE }}
